name: Update README with Blog Posts

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'  # Only run if workflow files change

jobs:
  update-readme:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y curl libxml2-utils

    - name: Fetch RSS feed
      id: fetch_rss
      run: |
        RSS_URL="https://kristianfreeman.com/feed/?type=rss"
        curl -s "$RSS_URL" | xmllint --xpath '//item/title | //item/link' - | \
        awk 'NR % 2 == 1 { title=$0; gsub(/<[^>]+>/, "", title); } NR % 2 == 0 { gsub(/<[^>]+>/, "", $0); print "- [" title "](" $0 ")" }' > posts.md

    - name: Prepare Markdown content
      id: prepare_markdown
      run: |
        if [ -f posts.md ] && [ -s posts.md ]; then
          echo "# Latest Blog Posts" > new_content.md
          cat posts.md >> new_content.md
          echo "[Why this exists](https://kristianfreeman.com/github-backlinks-rss/)" >> new_content.md
          NEW_CONTENT=$(cat new_content.md)
          echo "::set-output name=new_content::$NEW_CONTENT"
        else
          echo "::set-output name=new_content::"
        fi

    - name: Update README.md
      run: |
        if [ -s new_content.md ]; then
          rm README.md
          mv new_content.md README.md
          rm posts.md
        fi

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update README with latest blog posts"
        branch: main
